# Generated by Django 4.2.1 on 2023-05-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="clients_photos"),
        ),
    ]
